### ISSUE TITLE
No update

### ISSUE THREAD

**Issue by fredwiley** [CodeStix/Beat-360fyer-Plugin#13]
This is great mod, are you planning an update? I really miss it. It brings older maps back to life.

**Comment by CodeStix** [comment]
Glad to hear you like it. I plan on updating it next month after I graduate. Stay tuned 👍

**Comment by fredwiley** [comment]
Great news! Looking forward to it. I think a lot of people are.

**Comment by fiveseven808** [comment]
Definitely looking forward to an update please!!! This is my most favorite mod!!!

**Comment by manzanita0412** [comment]
@CodeStix still planning to do an update/version bump? Would be super awesome to have this plugin again!

**Comment by CodeStix** [comment]
Working on it!

**Comment by fredwiley** [comment]
Awesome!

**Comment by manzanita0412** [comment]
Looks like with the latest commits that the plug in is now compiling! ☺ It crashes when trying to generate the 360 map, but still good progress!

**Comment by CodeStix** [comment]
Update has been released! Enjoy! 🎉

**Comment by fredwiley** [comment]
You beauty! Thank you very much, it really is a great mod to have because it just adds an extra dimension and challenge to older maps and new simple maps.

Cheers!

**Comment by fredwiley** [comment]
Hello Stijn,

 

Plugin no longer works with v1.25.1?? Do you have time to update it? Otherwise I am sad.

 

Cheers,

Dave

**Comment by procedure1** [comment]
I have this working up to Beat Saber v1.24.1. Let me know if you want it. I'm not a programmer but its fairly easy to load the project into Visual Studio and update the manifest.json file to work with new versions of beat saber. But when I tried to do it for Beat Saber v1.25.1, I couldn't get it to work. Probably I missed something or its not compatible with one of the references or something. ugh.
-
Btw, I'm keeping my Beat Saber at v1.19 anyway since newer versions seem to have a bug where the background environment lights don't work anymore in 360 (the lasers still work on newer versions). 
What a nightmare keeping a plugin updated!
This is the greatest plugin of them all though, IMHO.
