### ISSUE TITLE
Only generate if 360/90 degree mode doesnt exist

### ISSUE THREAD

**Issue by Futuremappermydud** [CodeStix/Beat-360fyer-Plugin#7]

**Comment by Cartmanimm** [comment]
i kinda "loved" the bug. :c

**Comment by CodeStix** [comment]
@Cartmanimm  You can re-enable this by setting `AlwaysShowGenerated` to `true` in the config file, look [here](https://github.com/CodeStix/Beat-360fyer-Plugin/#config-file). 
& Yeah, I will probably be making this true by default in the future because sometimes the generated 360 mode is better than the original one :thinking:
